language: node_js
node_js:
  - "10.15.3"
cache:
  - npm
before script:
  - npm ci
script: 
  - npm run lint
  - npm run test
  - npm run build
  - now --token=$ZEIT_KEY -e BOT_TOKEN=$BOT_TOKEN
deploy:
   provider: pages
   skip-cleanup: true
   github-token: $GIT_TOKEN
on:
   branch: master
